version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log/host
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring
    depends_on:
      - nodejs-app

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring
    depends_on:
      - promtail

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3001:3000"
    networks:
      - monitoring
    depends_on:
      - loki

networks:
  monitoring:
    driver: bridge
